server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/OnlineLearning
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
 secret: super-secret-key-that-is-same-across-services


